### ISSUE TITLE
conduits not working

### ISSUE THREAD

**Issue by Trixz2018** [pupnewfster/GasConduits#2]
#### Issue Description:
gas conduits do not work with latest builds of mekanica and mekanism

#### Steps to reproduce:

1. connect gas conduit to gas tank and try to extract/insert into a empty gas tank
 

#### Versions (do not say latest):

- Gas Conduits:
- EnderIO: 5.0.40
- Mekanism: 9.6.5.357 Mekanica:  1.1.0a2
- Minecraft: 1.12
- Forge: 14.23.5.2815

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/8538100/54714353-b6d49d00-4b1e-11e9-8c41-1a3f17dfde74.png)

**Comment by Trixz2018** [comment]
![image](https://user-images.githubusercontent.com/8538100/54716276-60b62880-4b23-11e9-91bd-a5752015b3c8.png)

![image](https://user-images.githubusercontent.com/8538100/54716289-690e6380-4b23-11e9-82d0-e9bf6f920240.png)

**Comment by DroometYT** [comment]
how did you fix the problem? I have the same issue
