### ISSUE TITLE
Server Clash

### ISSUE THREAD

**Issue by dagantang** [pupnewfster/GasConduits#3]
#### Steps to reproduce:

1.

#### Versions (do not say latest):

- Gas Conduits:
- EnderIO:EnderIO-1.12.2-5.0.42
- Mekanism:Mekanism-1.12.2-9.6.7.360
- Minecraft:1.23.3
- Forge:2815

#### Your most recent log file where the issue was present: 
https://pastebin.com/4Hi0wBry

[pastebin/gist/etc link here]

**Comment by pupnewfster** [comment]
Update Ender IO the latest version of Gas Conduits requires 5.0.43
