### ISSUE TITLE
wrong version number for Mekanica dependency

### ISSUE THREAD

**Issue by LlubNek** [pupnewfster/GasConduits#4]
#### Issue Description:

GasConduits wants Mekanica version 1.12.2-9.7.0.  Latest version of Mekanica is 1.12.2-1.2.0.
Did you just copy Mekanism's version number by mistake?

#### Steps to reproduce:

1. start Minecraft with GasConduits, EnderIO and Mekanica (not Mekanism).
2. wait for error screen

#### Versions (do not say latest):

- Gas Conduits:
- EnderIO: 1.12.2-5.0.43
- Mekanism: none
- Mekanica: 1.12.2-1.2.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2835

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/pupnewfster/GasConduits/files/3076125/latest.log)

**Comment by pupnewfster** [comment]
This was a decision I made as until Mekanica splits off as its sister project (which its mod id will change) there is not an easy way to require specific versions. The 1.1.0 version for the most part should work fine with Mekanica 1.2.0. The 9.7.0 release of Mekanism includes all the changes in Mekanica plus a few more fixes.

Technically it *should* work against Mekanica 1.2, given I was testing the changes there but it is incompatible with versions < 1.2 and versions of Mekanism < 9.7.0 and given the modid is the same this is how I decided to do it.

**Comment by brachy84** [comment]
So I can't use Mekanica?

**Comment by pupnewfster** [comment]
Currently Mekanism 9.7.x is more up to date and contains all the changes of Mekanica (as well as various other fixes), once Mekanica fully splits off and changes the modid I will probably add support for it. Until then if you really want to use Mekanica over Mekanism 9.7.x I would recommend using Gas Conduits 1.1.0. This version unfortunately has a small bug with how the conduits interact with multitank things such as the electrolytic separator.

**Comment by McKitten** [comment]
Mekanica fixes quite a few of the lag issues that Mekanism (which is also bloated) has and I was annoyed that twitch decided to download the bloatware and conflict with Mekanica even after I had retrograded, this is probably twitch's programming tho any fault of yours.
Just please be aware as Mekanica gains more and more users your decision will become more acerbic.

**Comment by dizzyd** [comment]
Hi @McKitten - as @pupnewfster noted, we have merged all the lag fixes from Mekanica into Mekanism as of version 9.7. The Mekanism team plans to continue working on performance, while I'll be taking Mekanica in a different direction, as roughly described [here](https://www.reddit.com/r/feedthebeast/comments/bcg0c8/an_update_on_the_current_status_and_future_of/ekqnudv/). Hope that helps!
