### ISSUE TITLE
Broken Ender Gas Conduit GUI

### ISSUE THREAD

**Issue by Gameactive** [pupnewfster/GasConduits#5]
#### Issue Description:

Ender Gas Conduits have broken elements in their GUI that prevent them from working properly. Filters cannot be inserted, and insert/extract modes cannot be toggled in the GUI.

#### Steps to reproduce:

1. Open the Insert/Extract GUI on an Ender Gas Conduit.

#### Versions (do not say latest):

- Gas Conduits: 1.2.1
- EnderIO: 5.0.50
- Mekanism: 9.8.0.381
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Your most recent log file where the issue was present: 

VanillaFix generated this crash report: https://paste.dimdev.org/yunadexeza.mccrash

**Comment by pupnewfster** [comment]
Seems to be due to the Ender IO update. Probably not going to have a chance to fix it today, though hopefully tomorrow morning I can release a fix.

**Comment by pupnewfster** [comment]
I *think* I fixed it, however I am not going to upload the update until tomorrow as I have not had a chance to test my fixes, and ensure everything still works properly.

**Comment by pupnewfster** [comment]
Just as well I held off on uploading it as there were a couple bugs with filters not saving. I went ahead and uploaded a new version that is compatible with Ender IO 5.0.50: https://www.curseforge.com/minecraft/mc-mods/gas-conduits/files/2755340
