### ISSUE TITLE
Crash with the EnderIO-1.12.2-5.2.56

### ISSUE THREAD

**Issue by ChromaPIE** [pupnewfster/GasConduits#7]
#### Issue Description:
Might be due to some changes applied to the latest version of EnderIO, **EnderIO-1.12.2-5.2.56**, which was uploaded just now. The CR is [here](https://paste.ubuntu.com/p/3R2t3Z9V39/).

#### Steps to reproduce:

Put EnderIO-1.12.2-5.2.56 and GasConduits-1.12.2-1.2.2 in the same instance and try to launch the game.

#### Versions (do not say latest):

- Gas Conduits: **1.2.2**
- EnderIO: **5.2.56**
- Mekanism: **9.8.3.390**
- Minecraft: **1.12.2**
- Forge: **14.23.5.2854**

#### Your most recent log file where the issue was present: 

(Crash-report gave above)

**Comment by BedrockLegends** [comment]
Its cause Enderio Broke backwards Compatibility from what I understood

**Comment by pupnewfster** [comment]
I will release a build to fix this bug once EnderIO fixes the issues their maven is currently having.

**Comment by pupnewfster** [comment]
Fixed by https://github.com/pupnewfster/GasConduits/commit/79ca8c86fb8fb5abec63c97299900eaf4d820db5 release can be found here: https://www.curseforge.com/minecraft/mc-mods/gas-conduits/files/2989046
