### ISSUE TITLE
[1.12.2] Newest EnderIO crashes in world

### ISSUE THREAD

**Issue by YOYOK9** [pupnewfster/GasConduits#9]
#### Issue Description:
Modpack boots just fine. Its only when in a world with previously placed or newly placed conduits its crashes. 
Both Single player Worlds & server crash when a gas conduit is placed next to a mekanism machine. 
In a test I placed down all 3 conduit types. Unfortunately I'm not 100% sure if it was a certain conduit or not. Sp locks up and crashes. Server just closes 

#### Steps to reproduce:

1. place gas conduit in world.
2. place a mekanism machine that uses gas next to it. 

#### Versions (do not say latest):

- Gas Conduits: 1.12.2-1.2.3
- EnderIO: 1.12.2-5.2.60
- Mekanism: 1.12.2-9.8.3.390
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

#### Your most recent log file where the issue was present: 
Server Crash: https://pastebin.com/bMH1YRRk
SP Crash: https://pastebin.com/pednwzc5

[pastebin/gist/etc link here]

**Comment by pupnewfster** [comment]
File will be here: https://www.curseforge.com/minecraft/mc-mods/gas-conduits/files/3060489 once approved by CF
